project:
  type: website
  output-dir: docs

website:
  title: "Aditya Ranade"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/adityaranade
      - icon: linkedin
        href: https://www.linkedin.com/in/aditya-ranade-a3944349
format:
  html:
    theme: sketchy
    css: styles.css

editor: visual

